version: '3.9'
services:
  laravel-app:
    build:
      context: .
    container_name: "laravel"
    env_file: ./.env
    environment:
      APP_KEY: "base64:YjV5dmJiYzNmMjU0aWQ5cWJiaXY1NHRpNnQyYzFpemw="
    ports:
      - 8080:80
    restart: unless-stopped
